augmentation:
  color_jitter:
    brightness: 0.25
    contrast: 0.25
    saturation: 0.12
  horizontal_flip: 0.5
  rotation: 15
  scale_range:
  - 0.9
  - 1.1
data:
  batch_size: 32
  num_workers: 16
  root: data
  val_split: 0.1
experiment:
  description: Conservative tuning based on 0.6753 baseline - targeting 0.70-0.72
    F-Score
  name: optimized_v3_conservative
loss:
  ce_weight: 1.0
  dice_weight: 1.0
  use_class_weights: false
  use_focal: false
model:
  dropout: 0.12
  name: microsegformer
  num_classes: 19
output_dir: checkpoints/microsegformer_20251007_211559
training:
  early_stopping_patience: 80
  epochs: 300
  learning_rate: 7e-4
  max_grad_norm: 1.0
  optimizer: AdamW
  scheduler: CosineAnnealingLR
  use_amp: true
  warmup_epochs: 8
  weight_decay: 1e-4
