data:
  batch_size: 32
  num_workers: 4
  root: data
  val_split: 0.1
experiment:
  description: Use GPU-based augmentation (Kornia) for better GPU utilization
  name: lmsa_gpu_aug
gpu_augmentation:
  brightness: 0.2
  contrast: 0.2
  horizontal_flip_prob: 0.5
  rotation_degrees: 15
  saturation: 0.1
loss:
  ce_weight: 1.0
  dice_weight: 1.5
  use_class_weights: false
  use_focal: false
model:
  dropout: 0.15
  name: microsegformer
  num_classes: 19
  use_lmsa: true
output_dir: checkpoints/microsegformer_20251009_173630
training:
  early_stopping_patience: 30
  epochs: 200
  learning_rate: 8e-4
  max_grad_norm: 1.0
  optimizer: AdamW
  scheduler: CosineAnnealingLR
  use_amp: true
  use_gpu_augmentation: true
  warmup_epochs: 5
  weight_decay: 1e-4
