experiment:
  name: lmsa_gpu_aug
  description: Use GPU-based augmentation (Kornia) for better GPU utilization
model:
  name: microsegformer
  num_classes: 19
  use_lmsa: true
  dropout: 0.15
data:
  root: data
  batch_size: 32
  num_workers: 4
  val_split: 0.1
training:
  epochs: 200
  optimizer: AdamW
  learning_rate: 8e-4
  weight_decay: 1e-4
  scheduler: CosineAnnealingLR
  warmup_epochs: 5
  max_grad_norm: 1.0
  early_stopping_patience: 100
  use_amp: true
  use_gpu_augmentation: true
loss:
  ce_weight: 1.0
  dice_weight: 1.5
  use_focal: false
  use_class_weights: false
gpu_augmentation:
  horizontal_flip_prob: 0.5
  rotation_degrees: 15
  brightness: 0.2
  contrast: 0.2
  saturation: 0.1
