experiment:
  name: lmsa_continue_v2
  description: Continue from best model (0.6889) with enhanced regularization
model:
  name: microsegformer
  num_classes: 19
  use_lmsa: true
  dropout: 0.2
data:
  root: data
  batch_size: 32
  num_workers: 16
  val_split: 0.1
training:
  epochs: 200
  optimizer: AdamW
  learning_rate: 4e-4
  weight_decay: 2e-4
  scheduler: CosineAnnealingLR
  warmup_epochs: 0
  max_grad_norm: 1.0
  early_stopping_patience: 100
  use_amp: true
loss:
  ce_weight: 1.0
  dice_weight: 1.5
  use_focal: false
  use_class_weights: false
augmentation:
  horizontal_flip: 0.5
  rotation: 15
  scale_range:
  - 0.9
  - 1.1
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.1
