# Dice 2.5 + Label Smoothing + Strong Regularization
# Expected: Val 0.697-0.707, Test 0.74-0.75

experiment:
  name: lmsa_dice2.5_label_smooth
  description: "Dice 2.5 with label smoothing and strong regularization - aiming for 0.70+"

model:
  name: microsegformer
  num_classes: 19
  use_lmsa: true
  dropout: 0.2  # Strong regularization

data:
  root: data
  batch_size: 32
  num_workers: 8
  val_split: 0.1

augmentation:
  horizontal_flip: 0.5
  rotation: 15
  scale_range: [0.9, 1.1]
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.1

loss:
  ce_weight: 1.0
  dice_weight: 2.5  # Aggressive small object optimization
  use_focal: false
  use_class_weights: false
  label_smoothing: 0.1  # NEW: Prevent overconfidence

training:
  optimizer: AdamW
  learning_rate: 6e-4  # Slightly lower for stability
  weight_decay: 2e-4  # Higher regularization
  scheduler: CosineAnnealingLR
  warmup_epochs: 8  # Longer warmup
  epochs: 200
  early_stopping_patience: 100
  max_grad_norm: 1.0
  use_amp: true
