augmentation:
  color_jitter:
    brightness: 0.3
    contrast: 0.3
    saturation: 0.15
  horizontal_flip: 0.5
  rotation: 20
  scale_range:
  - 0.85
  - 1.15
data:
  batch_size: 32
  num_workers: 16
  root: data
  val_split: 0.1
experiment:
  description: Best config (0.6819) with enhanced augmentation for better generalization
  name: lmsa_strong_aug
loss:
  ce_weight: 1.0
  dice_weight: 1.0
  use_class_weights: false
  use_focal: false
model:
  dropout: 0.15
  name: microsegformer
  num_classes: 19
  use_lmsa: true
output_dir: checkpoints/microsegformer_20251008_030003
training:
  early_stopping_patience: null
  epochs: 300
  learning_rate: 8e-4
  max_grad_norm: 1.0
  optimizer: AdamW
  scheduler: CosineAnnealingLR
  use_amp: true
  warmup_epochs: 5
  weight_decay: 1e-4
