augmentation:
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.1
  horizontal_flip: 0.5
  rotation: 15
  scale_range:
  - 0.9
  - 1.1
data:
  batch_size: 32
  num_workers: 16
  root: data
  val_split: 0.1
experiment:
  description: U-Net baseline for comparison with MicroSegFormer - targeting 0.65+
    F-Score
  name: unet_baseline
loss:
  ce_weight: 1.0
  dice_weight: 1.0
  use_class_weights: false
  use_focal: false
model:
  base_channels: 20
  bilinear: true
  dropout: 0.15
  name: unet
  num_classes: 19
output_dir: checkpoints/unet_20251007_153812
training:
  early_stopping_patience: 50
  epochs: 200
  learning_rate: 8e-4
  max_grad_norm: 1.0
  optimizer: AdamW
  scheduler: CosineAnnealingLR
  use_amp: true
  warmup_epochs: 5
  weight_decay: 1e-4
